 



var heart_pattern = [
		"XXXXOOXXXXXXOOXXXX",
		"XXXOOOOXXXXOOOOXXX",
		"XXOOOOOOXXOOOOOOXX",
		"XOOOOOOOOOOOOOOOOX",
		"OOOOOOOOOOOOOOOOOO",
		"OOOOOOOOOOOOOOOOOO",
		"OOOOOOOOOOOOOOOOOO",
		"XOOOOOOOOOOOOOOOOX",
		"XXOOOOOOOOOOOOOOXX",
		"XXXOOOOOOOOOOOOXXX",
		"XXXXOOOOOOOOOOXXXX",
		"XXXXOOOOOOOOOOXXXX",
		"XXXXXOOOOOOOOXXXXX",
		"XXXXXOOOOOOOOXXXXX",
		"XXXXXXOOOOOOXXXXXX",
		"XXXXXXOOOOOOXXXXXX",
		"XXXXXXXXOOXXXXXXXX",
		"XXXXXXXXOOXXXXXXXX",
	]
